-- 002_source_health_persistence.sql
-- Persist per-run source health results for the CxA RFP Monitor.
--
-- V1 stores the data only. No dashboard UI reads these tables yet.

create extension if not exists pgcrypto;

create table if not exists public.source_health_runs (
    id uuid primary key default gen_random_uuid(),

    -- Monitor context
    monitor_type text not null,
    mode text,

    -- GitHub Actions context, useful for tracing a health run back to logs
    github_run_id text,
    github_run_attempt text,
    github_workflow text,

    -- Run timing
    run_started_at timestamptz not null default now(),
    run_completed_at timestamptz not null default now(),

    -- Summary counts
    total_records integer not null default 0,
    ok_count integer not null default 0,
    warn_count integer not null default 0,
    error_count integer not null default 0,

    -- Full summarized health-code counts, e.g. HEALTH_OK_NONZERO, HEALTH_WARN_ZERO
    summary jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now()
);

create table if not exists public.source_health_records (
    id bigserial primary key,

    -- Parent run
    run_id uuid not null references public.source_health_runs(id) on delete cascade,

    -- Monitor/source context
    monitor_type text not null,
    source_group text not null,
    source_name text not null,

    -- Health result
    code text not null,
    candidate_count integer,
    message text,

    -- Time the source-health record was generated by Python
    recorded_at timestamptz not null default now(),

    created_at timestamptz not null default now()
);

create index if not exists idx_source_health_runs_monitor_completed
    on public.source_health_runs (monitor_type, run_completed_at desc);

create index if not exists idx_source_health_runs_github_run
    on public.source_health_runs (github_run_id);

create index if not exists idx_source_health_records_run_id
    on public.source_health_records (run_id);

create index if not exists idx_source_health_records_monitor_code_recorded
    on public.source_health_records (monitor_type, code, recorded_at desc);

create index if not exists idx_source_health_records_source_recorded
    on public.source_health_records (source_name, recorded_at desc);

alter table public.source_health_runs enable row level security;
alter table public.source_health_records enable row level security;

-- V1 is server-side only. Do not expose these tables publicly yet.
-- GitHub Actions should write using the existing Supabase service-role key.
grant usage on schema public to service_role;

grant select, insert
on public.source_health_runs
to service_role;

grant select, insert
on public.source_health_records
to service_role;

grant usage, select
on sequence public.source_health_records_id_seq
to service_role;

-- No anon/authenticated RLS policies are added in V1.
-- If the GitHub Actions SUPABASE_KEY is not service-role level, persistence will
-- fail safely and we can add a narrower insert policy after confirming behavior.
